//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('ChessGames')
export class ChessGamesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  gameState: string;

  @Column('integer', { nullable: true })
  player1: number;

  @Column('integer', { nullable: true })
  player2: number;

  @Column('text', { nullable: true })
  gameResult: string;

  @Column('date', { nullable: true })
  gameStart: Date;

  @Column('date', { nullable: true })
  gameEnd: Date;
}
