//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('GameInvites')
export class GameInvitesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  sender: number;

  @Column('integer', { nullable: true })
  receiver: number;

  @Column('integer', { nullable: true })
  gameID: number;

  @Column('text', { nullable: true })
  inviteStatus: string;
}
