//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PlayerProfiles')
export class PlayerProfilesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  username: string;

  @Column('integer', { nullable: true })
  rating: number;

  @Column('integer', { nullable: true })
  gamesPlayed: number;

  @Column('text', { nullable: true })
  linkToFacebookProfile: string;
}
