//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ChessGamesTitle = () => {
  const record = useRecordContext();
  return <span>ChessGames {record ? `"${record.gameState}"` : ''}</span>;
};

export const ChessGamesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="gameState" />
      <ReferenceField source="player1" reference="PlayerProfiles" />
      <ReferenceField source="player2" reference="PlayerProfiles" />
      <TextField source="gameResult" />
      <DateField source="gameStart" />
      <DateField source="gameEnd" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ChessGamesEdit = () => (
  <Edit title={<ChessGamesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="gameState" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player1" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player2" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="gameResult" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="gameStart" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="gameEnd" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ChessGamesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="gameState" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player1" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player2" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="gameResult" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="gameStart" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="gameEnd" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="player1"
    label="player1"
    reference="PlayerProfiles"
    alwaysOn
  />,
  <ReferenceInput
    source="player2"
    label="player2"
    reference="PlayerProfiles"
    alwaysOn
  />,
  ,
  ,
  ,
];
