//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const GameInvitesTitle = () => {
  const record = useRecordContext();
  return <span>GameInvites {record ? `"${record.inviteStatus}"` : ''}</span>;
};

export const GameInvitesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="sender" reference="PlayerProfiles" />
      <ReferenceField source="receiver" reference="PlayerProfiles" />
      <ReferenceField source="gameID" reference="ChessGames" />
      <TextField source="inviteStatus" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const GameInvitesEdit = () => (
  <Edit title={<GameInvitesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="sender" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiver" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="gameID" reference="ChessGames" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="inviteStatus" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const GameInvitesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="sender" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="receiver" reference="PlayerProfiles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="gameID" reference="ChessGames" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="inviteStatus" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="sender"
    label="sender"
    reference="PlayerProfiles"
    alwaysOn
  />,
  <ReferenceInput
    source="receiver"
    label="receiver"
    reference="PlayerProfiles"
    alwaysOn
  />,
  <ReferenceInput
    source="gameID"
    label="gameID"
    reference="ChessGames"
    alwaysOn
  />,
  ,
];
