//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  PlayerProfilesList,
  PlayerProfilesCreate,
  PlayerProfilesEdit,
} from './resources/PlayerProfiles';
import {
  ChessGamesList,
  ChessGamesCreate,
  ChessGamesEdit,
} from './resources/ChessGames';
import {
  FriendListsList,
  FriendListsCreate,
  FriendListsEdit,
} from './resources/FriendLists';
import {
  GameInvitesList,
  GameInvitesCreate,
  GameInvitesEdit,
} from './resources/GameInvites';
import PlayerProfilesIcon from '@mui/icons-material/Person';
import ChessGamesIcon from '@mui/icons-material/Games';
import FriendListsIcon from '@mui/icons-material/People';
import GameInvitesIcon from '@mui/icons-material/Mail';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a95193c1a">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="PlayerProfiles"
          options={{ label: 'Player Profiles' }}
          list={PlayerProfilesList}
          create={PlayerProfilesCreate}
          edit={PlayerProfilesEdit}
          recordRepresentation="username"
          icon={PlayerProfilesIcon}
        />
        <Resource
          name="ChessGames"
          options={{ label: 'Chess Games' }}
          list={ChessGamesList}
          create={ChessGamesCreate}
          edit={ChessGamesEdit}
          recordRepresentation="gameState"
          icon={ChessGamesIcon}
        />
        <Resource
          name="FriendLists"
          options={{ label: 'Friend Lists' }}
          list={FriendListsList}
          create={FriendListsCreate}
          edit={FriendListsEdit}
          recordRepresentation="friendList"
          icon={FriendListsIcon}
        />
        <Resource
          name="GameInvites"
          options={{ label: 'Game Invites' }}
          list={GameInvitesList}
          create={GameInvitesCreate}
          edit={GameInvitesEdit}
          recordRepresentation="inviteStatus"
          icon={GameInvitesIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
